"""Phase 1 schema.

Card data, the physical collection, the audit log, auth, and the system tables.

Autogenerated from the models, then extended by hand with the SQLite-specific DDL
that SQLAlchemy's schema layer cannot express: the FTS5 external-content index over
``oracle_cards`` and the partial unique index that stops a copy being lent twice.

Revision ID: 0001_phase1
Revises:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_phase1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("password_set_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.Text(), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=True),
        sa.Column("batch_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("reverted_at", sa.Text(), nullable=True),
        sa.Column("revert_of_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_log_batch_id_ts", ["batch_id", "ts"], unique=False)
        batch_op.create_index(
            "ix_audit_log_entity_type_entity_id_ts",
            ["entity_type", "entity_id", "ts"],
            unique=False,
        )
        batch_op.create_index("ix_audit_log_ts", ["ts"], unique=False)

    op.create_table(
        "http_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("service", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("fetched_at", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.Text(), nullable=True),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("body_path", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_http_cache")),
        sa.UniqueConstraint("url_hash", name="http_cache_url_hash"),
    )
    with op.batch_alter_table("http_cache", schema=None) as batch_op:
        batch_op.create_index(
            "ix_http_cache_service_expires_at", ["service", "expires_at"], unique=False
        )

    op.create_table(
        "image_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("size", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("last_accessed_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_cache")),
        sa.UniqueConstraint("card_id", "size", name="image_cache_card_size"),
    )
    with op.batch_alter_table("image_cache", schema=None) as batch_op:
        batch_op.create_index("ix_image_cache_last_accessed_at", ["last_accessed_at"], unique=False)

    op.create_table(
        "import_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("started_at", sa.Text(), nullable=False),
        sa.Column("finished_at", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("rows_seen", sa.Integer(), nullable=False),
        sa.Column("rows_written", sa.Integer(), nullable=False),
        sa.Column("source_updated_at", sa.Text(), nullable=True),
        sa.Column("batch_id", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("detail_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_runs")),
    )
    with op.batch_alter_table("import_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_import_runs_kind_started_at", ["kind", "started_at"], unique=False
        )

    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_name", sa.Text(), nullable=False),
        sa.Column("sub_source", sa.Text(), nullable=True),
        sa.Column("started_at", sa.Text(), nullable=False),
        sa.Column("finished_at", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("detail_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
    )
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_job_runs_job_name_started_at", ["job_name", "started_at"], unique=False
        )

    op.create_table(
        "legality_changes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("oracle_id", sa.Text(), nullable=False),
        sa.Column("format", sa.Text(), nullable=False),
        sa.Column("old_status", sa.Text(), nullable=False),
        sa.Column("new_status", sa.Text(), nullable=False),
        sa.Column("detected_at", sa.Text(), nullable=False),
        sa.Column("import_run_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legality_changes")),
    )
    with op.batch_alter_table("legality_changes", schema=None) as batch_op:
        batch_op.create_index("ix_legality_changes_detected_at", ["detected_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_legality_changes_oracle_id"), ["oracle_id"], unique=False
        )

    op.create_table(
        "oracle_cards",
        sa.Column("oracle_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_norm", sa.Text(), nullable=False),
        sa.Column("name_front", sa.Text(), nullable=False),
        sa.Column("name_front_norm", sa.Text(), nullable=False),
        sa.Column("layout", sa.Text(), nullable=False),
        sa.Column("type_line", sa.Text(), nullable=True),
        sa.Column("oracle_text_all", sa.Text(), nullable=True),
        sa.Column("mana_cost", sa.Text(), nullable=True),
        sa.Column("cmc", sa.Float(), nullable=False),
        sa.Column("colors", sa.Text(), nullable=True),
        sa.Column("color_identity", sa.Text(), nullable=False),
        sa.Column("color_identity_mask", sa.Integer(), nullable=False),
        sa.Column("keywords_json", sa.JSON(), nullable=True),
        sa.Column("produced_mana", sa.Text(), nullable=True),
        sa.Column("is_legendary", sa.Boolean(), nullable=False),
        sa.Column("is_creature", sa.Boolean(), nullable=False),
        sa.Column("is_land", sa.Boolean(), nullable=False),
        sa.Column("reserved", sa.Boolean(), nullable=False),
        sa.Column("game_changer", sa.Boolean(), nullable=False),
        sa.Column("edhrec_rank", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("oracle_id", name=op.f("pk_oracle_cards")),
    )
    with op.batch_alter_table("oracle_cards", schema=None) as batch_op:
        batch_op.create_index(
            "ix_oracle_cards_ci_cmc", ["color_identity_mask", "cmc"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_oracle_cards_name_front_norm"), ["name_front_norm"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_oracle_cards_name_norm"), ["name_norm"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.Text(), nullable=False),
        sa.Column("last_seen_at", sa.Text(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index("ix_sessions_expires_at", ["expires_at"], unique=False)

    op.create_table(
        "settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "storage_locations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["storage_locations.id"],
            name=op.f("fk_storage_locations_parent_id_storage_locations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_locations")),
    )
    with op.batch_alter_table("storage_locations", schema=None) as batch_op:
        batch_op.create_index("ix_storage_locations_name", ["name"], unique=True)

    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scryfall_id", sa.Text(), nullable=False),
        sa.Column("oracle_id", sa.Text(), nullable=False),
        sa.Column("set_code", sa.Text(), nullable=False),
        sa.Column("set_name", sa.Text(), nullable=True),
        sa.Column("collector_number", sa.Text(), nullable=False),
        sa.Column("lang", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_front", sa.Text(), nullable=False),
        sa.Column("name_norm", sa.Text(), nullable=False),
        sa.Column("layout", sa.Text(), nullable=False),
        sa.Column("rarity", sa.Text(), nullable=True),
        sa.Column("mana_cost", sa.Text(), nullable=True),
        sa.Column("cmc", sa.Float(), nullable=False),
        sa.Column("type_line", sa.Text(), nullable=True),
        sa.Column("oracle_text", sa.Text(), nullable=True),
        sa.Column("colors", sa.Text(), nullable=True),
        sa.Column("color_identity", sa.Text(), nullable=False),
        sa.Column("color_identity_mask", sa.Integer(), nullable=False),
        sa.Column("keywords_json", sa.JSON(), nullable=True),
        sa.Column("produced_mana", sa.Text(), nullable=True),
        sa.Column("finishes_json", sa.JSON(), nullable=True),
        sa.Column("released_at", sa.Text(), nullable=True),
        sa.Column("illustration_id", sa.Text(), nullable=True),
        sa.Column("image_normal_url", sa.Text(), nullable=True),
        sa.Column("image_art_crop_url", sa.Text(), nullable=True),
        sa.Column("border_color", sa.Text(), nullable=True),
        sa.Column("frame", sa.Text(), nullable=True),
        sa.Column("promo", sa.Boolean(), nullable=False),
        sa.Column("variation", sa.Boolean(), nullable=False),
        sa.Column("digital", sa.Boolean(), nullable=False),
        sa.Column("reserved", sa.Boolean(), nullable=False),
        sa.Column("game_changer", sa.Boolean(), nullable=False),
        sa.Column("edhrec_rank", sa.Integer(), nullable=True),
        sa.Column("price_usd_cents", sa.Integer(), nullable=True),
        sa.Column("price_usd_foil_cents", sa.Integer(), nullable=True),
        sa.Column("price_usd_etched_cents", sa.Integer(), nullable=True),
        sa.Column("price_updated_at", sa.Text(), nullable=True),
        sa.Column("imported_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["oracle_id"],
            ["oracle_cards.oracle_id"],
            name=op.f("fk_cards_oracle_id_oracle_cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
        sa.UniqueConstraint("scryfall_id", name="cards_scryfall_id"),
        sa.UniqueConstraint("set_code", "collector_number", "lang", name="cards_natural"),
    )
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.create_index("ix_cards_illustration_id", ["illustration_id"], unique=False)
        batch_op.create_index(
            "ix_cards_lib_filter",
            ["color_identity_mask", "cmc", "rarity", "set_code"],
            unique=False,
        )
        batch_op.create_index("ix_cards_name_norm", ["name_norm"], unique=False)
        batch_op.create_index("ix_cards_oracle_id_lang", ["oracle_id", "lang"], unique=False)
        batch_op.create_index("ix_cards_price_usd_cents", ["price_usd_cents"], unique=False)

    op.create_table(
        "legalities",
        sa.Column("oracle_id", sa.Text(), nullable=False),
        sa.Column("format", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["oracle_id"],
            ["oracle_cards.oracle_id"],
            name=op.f("fk_legalities_oracle_id_oracle_cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("oracle_id", "format", name=op.f("pk_legalities")),
    )
    with op.batch_alter_table("legalities", schema=None) as batch_op:
        batch_op.create_index("ix_legalities_format_status", ["format", "status"], unique=False)

    op.create_table(
        "card_faces",
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("face_index", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("mana_cost", sa.Text(), nullable=True),
        sa.Column("type_line", sa.Text(), nullable=True),
        sa.Column("oracle_text", sa.Text(), nullable=True),
        sa.Column("colors", sa.Text(), nullable=True),
        sa.Column("image_normal_url", sa.Text(), nullable=True),
        sa.Column("image_art_crop_url", sa.Text(), nullable=True),
        sa.Column("illustration_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"], ["cards.id"], name=op.f("fk_card_faces_card_id_cards"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("card_id", "face_index", name=op.f("pk_card_faces")),
    )
    op.create_table(
        "collection_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("oracle_id", sa.Text(), nullable=False),
        sa.Column("set_code", sa.Text(), nullable=False),
        sa.Column("collector_number", sa.Text(), nullable=False),
        sa.Column("lang", sa.Text(), nullable=False),
        sa.Column("finish", sa.Text(), nullable=False),
        sa.Column("condition", sa.Text(), nullable=False),
        sa.Column("is_proxy", sa.Boolean(), nullable=False),
        sa.Column("storage_location_id", sa.Integer(), nullable=True),
        sa.Column("acquired_at", sa.Text(), nullable=True),
        sa.Column("acquired_price_cents", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_collection_items_card_id_cards"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["storage_location_id"],
            ["storage_locations.id"],
            name=op.f("fk_collection_items_storage_location_id_storage_locations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_items")),
    )
    with op.batch_alter_table("collection_items", schema=None) as batch_op:
        batch_op.create_index("ix_collection_items_card_id", ["card_id"], unique=False)
        batch_op.create_index("ix_collection_items_created_at", ["created_at"], unique=False)
        batch_op.create_index(
            "ix_collection_items_oracle_id_finish_is_proxy",
            ["oracle_id", "finish", "is_proxy"],
            unique=False,
        )
        batch_op.create_index(
            "ix_collection_items_storage_location_id_oracle_id",
            ["storage_location_id", "oracle_id"],
            unique=False,
        )

    op.create_table(
        "loans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("collection_item_id", sa.Integer(), nullable=False),
        sa.Column("person", sa.Text(), nullable=False),
        sa.Column("lent_at", sa.Text(), nullable=False),
        sa.Column("due_at", sa.Text(), nullable=True),
        sa.Column("returned_at", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_item_id"],
            ["collection_items.id"],
            name=op.f("fk_loans_collection_item_id_collection_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loans")),
    )
    with op.batch_alter_table("loans", schema=None) as batch_op:
        batch_op.create_index("ix_loans_collection_item_id", ["collection_item_id"], unique=False)

    # ### end Alembic commands ###

    # --- hand-written SQLite DDL ------------------------------------------------

    # A copy can be out on loan at most once. Expressing this as a partial unique
    # index makes it a database invariant rather than application discipline; the
    # same pattern is used for deck allocation in Phase 4.
    op.execute(
        "CREATE UNIQUE INDEX ix_loans_open ON loans(collection_item_id) WHERE returned_at IS NULL"
    )

    # Full-text search over oracle text (ADR-001). External-content FTS5 keeps the
    # text in oracle_cards and stores only the index here, so there is one copy of
    # the truth. remove_diacritics=2 makes "Lim-Dul" find "Lim-Dul's Vault".
    op.execute(
        "CREATE VIRTUAL TABLE oracle_text_fts USING fts5("
        "  name, type_line, oracle_text_all,"
        "  content='oracle_cards', content_rowid='rowid',"
        "  tokenize='unicode61 remove_diacritics 2'"
        ")"
    )
    op.execute(
        "CREATE TRIGGER oracle_cards_fts_ai AFTER INSERT ON oracle_cards BEGIN "
        "  INSERT INTO oracle_text_fts(rowid, name, type_line, oracle_text_all) "
        "  VALUES (new.rowid, new.name, new.type_line, new.oracle_text_all); "
        "END"
    )
    op.execute(
        "CREATE TRIGGER oracle_cards_fts_ad AFTER DELETE ON oracle_cards BEGIN "
        "  INSERT INTO oracle_text_fts(oracle_text_fts, rowid, name, type_line, "
        "                              oracle_text_all) "
        "  VALUES ('delete', old.rowid, old.name, old.type_line, old.oracle_text_all); "
        "END"
    )
    op.execute(
        "CREATE TRIGGER oracle_cards_fts_au AFTER UPDATE ON oracle_cards BEGIN "
        "  INSERT INTO oracle_text_fts(oracle_text_fts, rowid, name, type_line, "
        "                              oracle_text_all) "
        "  VALUES ('delete', old.rowid, old.name, old.type_line, old.oracle_text_all); "
        "  INSERT INTO oracle_text_fts(rowid, name, type_line, oracle_text_all) "
        "  VALUES (new.rowid, new.name, new.type_line, new.oracle_text_all); "
        "END"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS oracle_cards_fts_au")
    op.execute("DROP TRIGGER IF EXISTS oracle_cards_fts_ad")
    op.execute("DROP TRIGGER IF EXISTS oracle_cards_fts_ai")
    op.execute("DROP TABLE IF EXISTS oracle_text_fts")
    op.execute("DROP INDEX IF EXISTS ix_loans_open")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("loans", schema=None) as batch_op:
        batch_op.drop_index("ix_loans_collection_item_id")

    op.drop_table("loans")
    with op.batch_alter_table("collection_items", schema=None) as batch_op:
        batch_op.drop_index("ix_collection_items_storage_location_id_oracle_id")
        batch_op.drop_index("ix_collection_items_oracle_id_finish_is_proxy")
        batch_op.drop_index("ix_collection_items_created_at")
        batch_op.drop_index("ix_collection_items_card_id")

    op.drop_table("collection_items")
    op.drop_table("card_faces")
    with op.batch_alter_table("legalities", schema=None) as batch_op:
        batch_op.drop_index("ix_legalities_format_status")

    op.drop_table("legalities")
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.drop_index("ix_cards_price_usd_cents")
        batch_op.drop_index("ix_cards_oracle_id_lang")
        batch_op.drop_index("ix_cards_name_norm")
        batch_op.drop_index("ix_cards_lib_filter")
        batch_op.drop_index("ix_cards_illustration_id")

    op.drop_table("cards")
    with op.batch_alter_table("storage_locations", schema=None) as batch_op:
        batch_op.drop_index("ix_storage_locations_name")

    op.drop_table("storage_locations")
    op.drop_table("settings")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_sessions_expires_at")

    op.drop_table("sessions")
    with op.batch_alter_table("oracle_cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oracle_cards_name_norm"))
        batch_op.drop_index(batch_op.f("ix_oracle_cards_name_front_norm"))
        batch_op.drop_index("ix_oracle_cards_ci_cmc")

    op.drop_table("oracle_cards")
    with op.batch_alter_table("legality_changes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_legality_changes_oracle_id"))
        batch_op.drop_index("ix_legality_changes_detected_at")

    op.drop_table("legality_changes")
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_job_runs_job_name_started_at")

    op.drop_table("job_runs")
    with op.batch_alter_table("import_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_import_runs_kind_started_at")

    op.drop_table("import_runs")
    with op.batch_alter_table("image_cache", schema=None) as batch_op:
        batch_op.drop_index("ix_image_cache_last_accessed_at")

    op.drop_table("image_cache")
    with op.batch_alter_table("http_cache", schema=None) as batch_op:
        batch_op.drop_index("ix_http_cache_service_expires_at")

    op.drop_table("http_cache")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_log_ts")
        batch_op.drop_index("ix_audit_log_entity_type_entity_id_ts")
        batch_op.drop_index("ix_audit_log_batch_id_ts")

    op.drop_table("audit_log")
    op.drop_table("app_user")
    # ### end Alembic commands ###
