"""Phase 2: scan sessions, scan events, idempotency keys.

Revision ID: 0002_phase2_scan
Revises: 0001_phase1
Created: 2026-08-23 09:03:50.880663
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002_phase2_scan"
down_revision: str | None = "0001_phase1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_idempotency_keys")),
    )
    with op.batch_alter_table("idempotency_keys", schema=None) as batch_op:
        batch_op.create_index("ix_idempotency_keys_created_at", ["created_at"], unique=False)

    op.create_table(
        "scan_sessions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("started_at", sa.Text(), nullable=False),
        sa.Column("ended_at", sa.Text(), nullable=True),
        sa.Column("device", sa.Text(), nullable=True),
        sa.Column("added_count", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_sessions")),
    )
    with op.batch_alter_table("scan_sessions", schema=None) as batch_op:
        batch_op.create_index("ix_scan_sessions_started_at", ["started_at"], unique=False)

    op.create_table(
        "scan_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=True),
        sa.Column("first_match_card_id", sa.Integer(), nullable=True),
        sa.Column("first_match_oracle_id", sa.Text(), nullable=True),
        sa.Column("confirmed_card_id", sa.Integer(), nullable=True),
        sa.Column("confirmed_oracle_id", sa.Text(), nullable=True),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("ocr_confidence", sa.Float(), nullable=True),
        sa.Column("fuzz_score", sa.Float(), nullable=True),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("cached", sa.Boolean(), nullable=False),
        sa.Column("dhash", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["scan_sessions.id"],
            name=op.f("fk_scan_events_session_id_scan_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_events")),
    )
    with op.batch_alter_table("scan_events", schema=None) as batch_op:
        batch_op.create_index("ix_scan_events_session_id_ts", ["session_id", "ts"], unique=False)
        batch_op.create_index("ix_scan_events_ts", ["ts"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan_events", schema=None) as batch_op:
        batch_op.drop_index("ix_scan_events_ts")
        batch_op.drop_index("ix_scan_events_session_id_ts")

    op.drop_table("scan_events")
    with op.batch_alter_table("scan_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_scan_sessions_started_at")

    op.drop_table("scan_sessions")
    with op.batch_alter_table("idempotency_keys", schema=None) as batch_op:
        batch_op.drop_index("ix_idempotency_keys_created_at")

    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
